const text = [
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis aenean et tortor at risus viverra adipiscing. Aliquam sem et tortor consequat id porta nibh venenatis. Id donec ultrices tincidunt arcu non. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Tellus elementum sagittis vitae et. Neque laoreet suspendisse interdum consectetur libero id faucibus. Semper viverra nam libero justo laoreet sit amet cursus. Pharetra vel turpis nunc eget lorem dolor. Tellus pellentesque eu tincidunt tortor. Commodo odio aenean sed adipiscing diam donec adipiscing.`,
  `Cursus in hac habitasse platea dictumst quisque. Blandit libero volutpat sed cras ornare arcu dui vivamus arcu. Sit amet porttitor eget dolor morbi. Amet est placerat in egestas erat imperdiet sed euismod. Gravida arcu ac tortor dignissim convallis. Aliquet eget sit amet tellus cras. Massa sed elementum tempus egestas sed sed risus. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim. Ac orci phasellus egestas tellus rutrum tellus. Ut morbi tincidunt augue interdum velit. Non sodales neque sodales ut etiam sit amet. Velit euismod in pellentesque massa placerat duis. Sagittis purus sit amet volutpat consequat mauris nunc congue. Arcu odio ut sem nulla pharetra. Urna cursus eget nunc scelerisque viverra mauris in aliquam. Sit amet massa vitae tortor condimentum lacinia. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Nullam vehicula ipsum a arcu cursus vitae congue mauris.`,
  `Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Iaculis urna id volutpat lacus laoreet non curabitur gravida. Ornare aenean euismod elementum nisi quis. Pretium aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Dictumst quisque sagittis purus sit amet volutpat. Vulputate sapien nec sagittis aliquam malesuada. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Non curabitur gravida arcu ac tortor dignissim convallis aenean. In vitae turpis massa sed elementum tempus egestas. Turpis egestas maecenas pharetra convallis posuere morbi leo. Nullam vehicula ipsum a arcu cursus vitae. Cras sed felis eget velit aliquet sagittis id.`,
  `Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Et tortor at risus viverra adipiscing at in tellus integer. Ac feugiat sed lectus vestibulum. Aliquet sagittis id consectetur purus. Sed odio morbi quis commodo odio aenean sed. Felis donec et odio pellentesque diam. Sapien et ligula ullamcorper malesuada proin libero nunc. Adipiscing elit ut aliquam purus sit amet. Bibendum at varius vel pharetra vel turpis nunc. Ultrices vitae auctor eu augue ut lectus arcu. Enim tortor at auctor urna nunc. Proin fermentum leo vel orci. Amet massa vitae tortor condimentum. Condimentum mattis pellentesque id nibh tortor id aliquet. Faucibus in ornare quam viverra orci sagittis eu volutpat. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Urna molestie at elementum eu facilisis sed odio.`,
  `Id nibh tortor id aliquet lectus proin nibh. Scelerisque purus semper eget duis at tellus at urna condimentum. Blandit turpis cursus in hac habitasse platea. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Scelerisque viverra mauris in aliquam. Ante in nibh mauris cursus mattis molestie a. Amet commodo nulla facilisi nullam. Diam vulputate ut pharetra sit. Urna condimentum mattis pellentesque id nibh tortor. Lobortis mattis aliquam faucibus purus in massa tempor. Est placerat in egestas erat imperdiet sed euismod nisi porta. Quis vel eros donec ac odio tempor orci. Tortor aliquam nulla facilisi cras. Dui faucibus in ornare quam viverra orci. Aenean euismod elementum nisi quis eleifend quam adipiscing vitae proin. Congue mauris rhoncus aenean vel elit scelerisque. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Feugiat in ante metus dictum at tempor commodo ullamcorper a.`,
  `Fringilla phasellus faucibus scelerisque eleifend donec pretium. Morbi enim nunc faucibus a pellentesque sit amet porttitor. At tellus at urna condimentum mattis. Placerat in egestas erat imperdiet sed euismod nisi. Turpis massa sed elementum tempus. Vivamus at augue eget arcu dictum varius duis at. Imperdiet dui accumsan sit amet nulla. Diam quam nulla porttitor massa id. Sed pulvinar proin gravida hendrerit. Id faucibus nisl tincidunt eget. Volutpat consequat mauris nunc congue. Diam maecenas sed enim ut sem viverra. A lacus vestibulum sed arcu non odio euismod lacinia. Morbi non arcu risus quis varius quam quisque. Sagittis vitae et leo duis ut.`,
  `Amet nisl suscipit adipiscing bibendum est. Sed velit dignissim sodales ut. Volutpat blandit aliquam etiam erat velit. Ut diam quam nulla porttitor massa id neque aliquam. Sodales neque sodales ut etiam sit amet nisl. Non sodales neque sodales ut etiam sit. Malesuada fames ac turpis egestas. Semper quis lectus nulla at volutpat diam ut venenatis tellus. Vel orci porta non pulvinar. Commodo quis imperdiet massa tincidunt nunc. Sit amet volutpat consequat mauris nunc congue. Sed sed risus pretium quam vulputate dignissim suspendisse in est. Nec ultrices dui sapien eget mi proin sed. Porta nibh venenatis cras sed felis eget velit aliquet. Suspendisse sed nisi lacus sed viverra tellus. Volutpat odio facilisis mauris sit amet. Mi bibendum neque egestas congue quisque egestas diam in. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Elementum eu facilisis sed odio morbi quis commodo odio aenean.`,
  `Iaculis urna id volutpat lacus laoreet non curabitur gravida. Lectus sit amet est placerat in egestas erat imperdiet. Nibh tortor id aliquet lectus proin. Sit amet consectetur adipiscing elit. Nisi quis eleifend quam adipiscing vitae proin sagittis. Id ornare arcu odio ut sem. A iaculis at erat pellentesque adipiscing commodo elit at. Sed id semper risus in hendrerit gravida rutrum quisque non. Ut tristique et egestas quis ipsum suspendisse ultrices. Arcu non odio euismod lacinia at quis risus sed vulputate. Id consectetur purus ut faucibus pulvinar. Ornare arcu dui vivamus arcu felis bibendum. Pharetra sit amet aliquam id diam. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Semper auctor neque vitae tempus quam pellentesque nec nam aliquam. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel.`,
  `Aenean vel elit scelerisque mauris pellentesque pulvinar. Adipiscing commodo elit at imperdiet dui accumsan. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Praesent semper feugiat nibh sed pulvinar proin gravida. Egestas sed sed risus pretium quam. Pellentesque id nibh tortor id aliquet lectus proin. Pellentesque nec nam aliquam sem et tortor consequat id porta. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt. Vitae suscipit tellus mauris a diam maecenas sed enim. Nulla facilisi nullam vehicula ipsum a arcu cursus.`,
  `Cursus in hac habitasse platea dictumst quisque. At varius vel pharetra vel turpis nunc eget lorem. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus. Amet luctus venenatis lectus magna fringilla. Lectus sit amet est placerat. A condimentum vitae sapien pellentesque habitant. Congue eu consequat ac felis. Quisque sagittis purus sit amet volutpat consequat mauris. Ornare suspendisse sed nisi lacus sed viverra. Lobortis elementum nibh tellus molestie.`,
  `Activated charcoal direct trade palo santo vape everyday carry pork belly mustache kitsch gochujang. Vexillologist shoreditch deep v, keytar ethical seitan sartorial kale chips irony tumeric microdosing brunch. Keffiyeh master cleanse next level, glossier lumbersexual shaman af edison bulb distillery knausgaard vape small batch portland. Cred truffaut vape deep v +1, gastropub hot chicken raw denim helvetica umami offal.`,
  `Dreamcatcher sartorial asymmetrical crucifix wolf godard, coloring book squid freegan affogato lumbersexual franzen. Drinking vinegar vape chillwave pinterest tofu pug hella sartorial neutra cray tumeric. Poke cloud bread XOXO salvia. Glossier jean shorts craft beer gastropub, squid pitchfork humblebrag listicle taiyaki messenger bag retro thundercats subway tile raw denim. Hoodie asymmetrical food truck listicle pour-over.`,
  `Pop-up tote bag twee squid asymmetrical lyft roof party ugh try-hard glossier pabst bicycle rights jean shorts single-origin coffee. IPhone tumblr narwhal, tattooed mumblecore you probably haven't heard of them XOXO authentic art party bicycle rights. Bespoke bitters master cleanse austin authentic lumbersexual mixtape man bun art party tilde swag. Tacos bitters chicharrones thundercats selfies chartreuse chia. Put a bird on it taxidermy cornhole VHS, tousled ennui fam hexagon craft beer marfa DIY pinterest.`,
  `Air plant deep v polaroid church-key. Farm-to-table ramps put a bird on it pickled aesthetic pork belly beard tbh street art pabst. Pop-up cliche before they sold out hoodie heirloom flannel schlitz organic. Crucifix forage cardigan before they sold out umami echo park subway tile art party squid shoreditch photo booth.`,
  `Yr offal cornhole neutra. Cronut kale chips hoodie, mustache tilde tacos palo santo fashion axe whatever pop-up post-ironic pitchfork pok pok ethical. Literally freegan post-ironic wolf listicle synth gochujang tousled palo santo 3 wolf moon health goth next level. Asymmetrical you probably haven't heard of them lomo post-ironic, pitchfork crucifix narwhal retro chia tofu schlitz. Kitsch keytar normcore listicle flexitarian fashion axe chartreuse jianbing yr vice flannel cred.`,
  `Jianbing live-edge bicycle rights messenger bag, street art offal squid gastropub food truck kale chips locavore. Mustache humblebrag banjo, shaman offal photo booth coloring book mumblecore typewriter tbh you probably haven't heard of them. Disrupt glossier umami pop-up, schlitz listicle keytar ramps. Try-hard tumblr crucifix aesthetic lyft.`,
  `Try-hard woke irony selvage listicle, literally adaptogen tilde messenger bag deep v hexagon stumptown gastropub. YOLO yuccie godard copper mug, slow-carb put a bird on it williamsburg offal craft beer trust fund sustainable palo santo 8-bit. Venmo XOXO drinking vinegar kale chips cred semiotics, vinyl helvetica hoodie bespoke leggings pop-up. Polaroid lomo tofu vape. Chicharrones mumblecore taiyaki, direct trade prism vinyl cardigan subway tile flexitarian. Aesthetic food truck glossier coloring book. Biodiesel distillery crucifix schlitz skateboard ennui master cleanse pok pok normcore cardigan.`,
  `Cliche organic woke yr gluten-free, twee PBR&B everyday carry 8-bit roof party. Hexagon craft beer pinterest humblebrag raw denim pabst schlitz celiac. Quinoa hoodie man braid, iPhone flannel chia scenester pinterest kickstarter enamel pin health goth aesthetic art party cliche mustache. Irony cred street art locavore green juice.`,
  `Tilde twee af drinking vinegar trust fund. Ramps vaporware hell of kombucha 8-bit chambray YOLO wolf vinyl pop-up cornhole activated charcoal mixtape. Mixtape marfa before they sold out XOXO poutine craft beer scenester cronut drinking vinegar knausgaard you probably haven't heard of them hella. Literally selvage mumblecore activated charcoal echo park vegan deep v fingerstache irony kogi microdosing trust fund. Schlitz cloud bread activated charcoal, master cleanse kitsch shoreditch umami bicycle rights la croix post-ironic biodiesel edison bulb. 8-bit disrupt banjo selvage. Flannel selfies organic put a bird on it keytar, lo-fi health goth umami fam four loko kombucha adaptogen hammock austin tilde.`
]

const form = document.querySelector(".lorem-form");
const numofpara = document.getElementById("numofpara");
const numofparaRange = document.getElementById("numofparaRange");
const result = document.querySelector(".lorem-text");

function syncParaNumbers(e) {
  const value = e.target.value;
  numofpara.value = value;
  numofparaRange.value = value;
}

form.addEventListener('submit', e => {
  e.preventDefault()
  const value = parseInt(numofpara.value);
  let tempText = text.slice(0, value);
  tempText = tempText.map(item => `<p class="result">${item}</p>`).join("");
  result.innerHTML = tempText;
})

numofpara.addEventListener('input', syncParaNumbers)
numofparaRange.addEventListener('input', syncParaNumbers)